In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sys
from pathlib import Path

In [2]:
sys.path.append(str(Path.cwd().parent))

from tables import create_shots_target_table

from tables import create_shots_target_against_table

In [3]:
url = "https://raw.githubusercontent.com/kkathait/D501_Final_Project/refs/heads/main/combined_data.csv"

sot = create_shots_target_table(url)

sot_against = create_shots_target_against_table(url)

In [4]:
sot

,Team,Games,Shots on Target Home,Percent SOT Home,Shots on Target Away,Percent SOT Away
0,Arsenal,266,734,0.34,571,0.34
1,Aston Villa,266,652,0.36,528,0.35
2,Bournemouth,190,421,0.34,398,0.35
3,Brentford,190,444,0.37,375,0.39
4,Brighton,266,653,0.32,590,0.36
5,Burnley,190,353,0.32,296,0.34
6,Chelsea,266,756,0.35,642,0.36
7,Crystal Palace,266,538,0.33,492,0.37
8,Everton,266,589,0.35,461,0.33
9,Fulham,190,398,0.32,376,0.34
10,Ipswich,38,68,0.33,59,0.35
11,Leeds,152,345,0.33,304,0.34
12,Leicester,190,411,0.36,396,0.37
13,Liverpool,266,871,0.35,725,0.35
14,Luton,38,84,0.32,57,0.34
15,Man City,266,864,0.36,791,0.37
16,Man United,266,779,0.36,633,0.37
17,Newcastle,266,669,0.34,512,0.36
18,Norwich,76,136,0.32,104,0.29
19,Nott'm Forest,152,305,0.32,283,0.36
20,Sheffield United,114,201,0.34,142,0.32
21,Southampton,190,395,0.36,375,0.35
22,Sunderland,38,65,0.29,61,0.37
23,Tottenham,266,692,0.37,591,0.38
24,Watford,76,131,0.28,116,0.32
25,West Brom,38,59,0.34,53,0.32
26,West Ham,266,562,0.35,507,0.33
27,Wolves,266,540,0.34,462,0.33

In [5]:
sot_against

,Team,Games,SOT Allowed Home,Percent SOT Allowed Home,SOT Allowed Away,Percent SOT Allowed Away
0,Arsenal,266,413,0.34,493,0.33
1,Aston Villa,266,544,0.35,655,0.34
2,Bournemouth,190,404,0.34,530,0.35
3,Brentford,190,424,0.33,522,0.35
4,Brighton,266,477,0.35,569,0.34
5,Burnley,190,477,0.37,529,0.32
6,Chelsea,266,456,0.35,558,0.37
7,Crystal Palace,266,534,0.35,598,0.33
8,Everton,266,546,0.34,651,0.33
9,Fulham,190,416,0.39,464,0.37
10,Ipswich,38,106,0.39,110,0.33
11,Leeds,152,346,0.36,441,0.38
12,Leicester,190,392,0.33,475,0.36
13,Liverpool,266,439,0.37,527,0.38
14,Luton,38,101,0.38,131,0.34
15,Man City,266,352,0.38,417,0.35
16,Man United,266,491,0.33,608,0.33
17,Newcastle,266,565,0.34,667,0.36
18,Norwich,76,225,0.39,219,0.33
19,Nott'm Forest,152,305,0.32,394,0.34
20,Sheffield United,114,295,0.39,326,0.37
21,Southampton,190,476,0.37,475,0.37
22,Sunderland,38,68,0.30,99,0.31
23,Tottenham,266,554,0.34,615,0.33
24,Watford,76,193,0.38,183,0.33
25,West Brom,38,129,0.41,117,0.41
26,West Ham,266,611,0.35,698,0.34
27,Wolves,266,561,0.35,644,0.34